server:
    port: 3000

spring:
  application:
    name: wzy-crowd-redis
  redis:
    host: 192.168.200.130
    password: wzy134679

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
  instance:
    hostname: localhost