server:
    port: 2000

spring:
  application:
    name: wzy-crowd-mysql
  datasource:
#    name: mydb
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/project_crowd
    username: root
    password: 134679
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost


logging:
  level:
    wzy.crowd.mapper: debug